setwd("/Users/harshitha.ramesh/Documents/datasciencecoursera/GettingCleaningDataProject/UCIHARDataset")
library(dplyr)
library(reshape)
dataset_1 <- read.table("test/X_test.txt")
dataset_2 <- read.table("train/X_train.txt")
data <- rbind(dataset_1,dataset_2)
subject_1 <- read.table("test/subject_test.txt")
subject_2 <- read.table("train/subject_train.txt")
subjects <- rbind(subject_1,subject_2)
activity_1 <- read.table("test/y_test.txt")
activity_2 <- read.table("train/y_train.txt")
activities <- rbind(activity_1,activity_2)
data <- cbind(subjects,activities,data)
measurements <- read.table("features.txt")
measurements$V2 <- as.character(measurements$V2)
mean_measurements <- grep("mean",measurements$V2)
std_measurements <- grep("std",measurements$V2)
needed_measurements <- c(mean_measurements+2,std_measurements+2)
data <- data[,c(1,2,needed_measurements)]
activity_labels <- read.table("activity_labels.txt")
data <- merge(x = data,y = activity_labels, by.x = "V1.1", by.y = "V1", all.x=TRUE)    
names(data) <- c("Activity_Number","Subject_Number",measurements$V2[mean_measurements],measurements$V2[std_measurements],"Activity")
data <- data[c("Subject_Number","Activity",measurements$V2[mean_measurements],measurements$V2[std_measurements])]
data$Activity <- as.factor(data$Activity)
data$Subject_Number <- as.factor(as.double(data$Subject_Number))
data %>% group_by(Subject_Number, Activity) %>% summarize_each(funs(mean)) %>% write.table(file = "tidydata.txt",row.name = FALSE)

